apiVersion: v1
kind: Template
metadata:
  name: hono-demo-1-template
  annotations:
    description: "Eclipse Hono™ Demo #1"
    iconClass: "pficon pficon-virtual-machine"
    tags: "iot"

# Parameters

parameters:
- name:         GIT_URI
  description:     URI of the git repository to use
  value:           https://github.com/ctron/hono-demo-1
- name:         GIT_BRANCH
  description:     GitHub branch
  value:           master
- name:         ENMASSE_PROJECT
  description:     The project name of the EnMasse instance
  value:           enmasse
- name:         HONO_PROJECT
  description:     The project name of the Hono instance
  value:           hono

objects:

# Image streams

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: hono-demo-1-base

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: hono-demo-1-consumer-influxdb

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: hono-demo-1-dataset-simulator

# Builds

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: hono-demo-1-base-build
  spec:
    triggers: 
      - type: ImageChange
      - type: ConfigChange
    source: 
      type: Git
      git:
        uri: ${GIT_URI}
        ref: ${GIT_BRANCH}
    strategy: 
      type: Docker
      dockerStrategy:
        dockerfilePath: base.Dockerfile
    postCommit:
    output: 
      to:
        kind: ImageStreamTag
        name: hono-demo-1-base:latest

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: hono-demo-1-consumer-influxdb-build
  spec:
    triggers: 
      - type: ImageChange
      - type: ConfigChange
    source: 
      type: Git
      git:
        uri: ${GIT_URI}
        ref: ${GIT_BRANCH}
    strategy: 
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: hono-demo-1-base:latest
        dockerfilePath: consumer-influxdb.Dockerfile
    postCommit:
    output: 
      to:
        kind: ImageStreamTag
        name: hono-demo-1-consumer-influxdb:latest

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: hono-demo-1-dataset-simulator-build
  spec:
    triggers: 
      - type: ImageChange
      - type: ConfigChange
    source: 
      type: Git
      git:
        uri: ${GIT_URI}
        ref: ${GIT_BRANCH}
    strategy: 
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: hono-demo-1-base:latest
        dockerfilePath: dataset-simulator.Dockerfile
    postCommit:
    output: 
      to:
        kind: ImageStreamTag
        name: hono-demo-1-dataset-simulator:latest

# Deployment

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: hono-demo-1-consumer-influxdb
  spec:
    replicas: 1
    selector:
      app: hono-demo-1-consumer-influxdb
      deploymentconfig: hono-demo-1-consumer-influxdb
    strategy:
      type: Recreate
    triggers:
      - type: ConfigChange 
      - type: ImageChange 
        imageChangeParams:
          automatic: true
          containerNames:
            - consumer-influxdb
          from:
            kind: ImageStreamTag
            name: hono-demo-1-consumer-influxdb:latest
    template:
      metadata:
        labels:
          app: hono-demo-1-consumer-influxdb
          deploymentconfig: hono-demo-1-consumer-influxdb
      spec:
        containers:
        - image: hono-demo-1-consumer-influxdb
          imagePullPolicy: Always
          name: consumer-influxdb
#          volumeMounts:
#            - name: secret-volume
#              mountPath: /etc/secret-volume
#              readOnly: true
          env:
            - name: HONO_USER
              value: consumer@HONO
            - name: HONO_PASSWORD
              value: verysecret
            - name: HONO_TENANT
              value: DEFAULT_TENANT
            - name: MESSAGING_SERVICE_HOST
              value: messaging.${ENMASSE_PROJECT}.svc
            - name: MESSAGING_SERVICE_PORT_AMQP
              value: 5672
#            - name: HONO_TRUSTED_CERTS
#              value: /etc/secret-volume/trusted-certs.pem
            - name: INFLUXDB_USER
              value: root
            - name: INFLUXDB_PASSWORD
              value: root
            - name: INFLUXDB_NAME
              value: kubecon
            - name: INFLUXDB_URL
              value: http://influxdb.${HONO_PROJECT}.svc:8086
            - name: DISABLE_TLS
              value: "true"
#        volumes:
#          - name: secret-volume
#            secret:
#              secretName: hono-dispatch-router-conf

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: hono-demo-1-dataset-simulator
  spec:
    replicas: 1
    selector:
      app: hono-demo-1-dataset-simulator
      deploymentconfig: hono-demo-1-dataset-simulator
    strategy:
      type: Recreate
    triggers:
      - type: ConfigChange 
      - type: ImageChange 
        imageChangeParams:
          automatic: true
          containerNames:
            - dataset-simulator
          from:
            kind: ImageStreamTag
            name: hono-demo-1-dataset-simulator:latest
    template:
      metadata:
        labels:
          app: hono-demo-1-dataset-simulator
          deploymentconfig: hono-demo-1-dataset-simulator
      spec:
        containers:
        - image: hono-demo-1-dataset-simulator
          imagePullPolicy: Always
          name: dataset-simulator
          env:
            - name: DATASET_FILE
              value: /build/src/dataset/Electricity_P.csv
            - name: NUMBER_OF_FLOWS
              value: "1"
            - name: NUMBER_OF_PUBLISHERS
              value: "1"
            - name: HONO_ADAPTER_MQTT_VERTX_SERVICE_HOST
              value: hono-adapter-mqtt-vertx.${HONO_PROJECT}.svc
            - name: HONO_ADAPTER_MQTT_VERTX_SERVICE_PORT
              value: "8883"
            - name: HONO_SERVICE_DEVICE_REGISTRY_URL
              value: http://hono-service-device-registry.${HONO_PROJECT}.svc:8080
